# Generated by Django 6.0.6 on 2026-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar_letter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscribers",
        ),
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_covers/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
