# Generated by Django 6.0.6 on 2026-06-21 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_profile_avatar_letter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
