# Generated by Django 6.0.6 on 2026-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_profile_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
